[build]
target = "xtensa-esp32s3-espidf"

[target.'cfg(target_os = "espidf")']
# Use the xtensa GCC installed by espup as the linker. Adjust path if your espup toolchain is elsewhere.
linker = "/home/viktor/.cargo/bin/ldproxy"
runner = "espflash flash --monitor"
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32s3"
ESP_IDF_VERSION = "v5.5.3"
ESP_IDF_TOOLS_INSTALL_DIR = "workspace"

# Uncomment this if you have moved the target dir by setting CARGO_TARGET_DIR or similar.
# Required for now due to embuild limitations.
#CARGO_WORKSPACE_DIR = { value = "", relative = true }
